### PR TITLE
Update to support Laravel 8.0

### PR DESCRIPTION
**Pull request by ryanhalliday**
Based on the [Upgrade Guide](https://laravel.com/docs/8.x/upgrade) there shouldn't be any breaking changes. I searched the code for the functions that had major changes and there were no results.

There are no tests to run so I can't be too sure - happy to hear your thoughts on this? 

Ready to make any changes needed. Thanks!

### CODE REVIEW

**Comment by ssi-anik** [comment]
First of all, thanks for the PR. 
I am sorry to notify you this late. was busy recently. After checking your PR, I found that the `composer.lock` file should not be in the package. I have removed the file from the remote. can you please resolve the conflict?

**Comment by ryanhalliday** [comment]
No problem - made that change now so should be good to merge

**Comment by ssi-anik** [comment]
Merged and thanks.

**Comment by ryanhalliday** [comment]
@ssi-anik Would you be able to tag a release for this? Thanks!

**Comment by ssi-anik** [comment]
Sorry for the delay. I've just released a new tag `v1.4`.

**Pull request merged**
